### ISSUE TITLE
Upgrade to node 20

### ISSUE THREAD

**Issue by aabeling** [clowdhaus/aws-github-actions#21]
### Is your feature request related to a problem? Please describe

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: clowdhaus/aws-github-actions/iam_access_credentials@main, clowdhaus/aws-github-actions/awscli@main. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

### Describe the solution you wouldd like

Upgrade to node 20

**Comment by bryantbiggs** [comment]
Fixed in https://github.com/clowdhaus/aws-github-actions/releases/tag/v0.8.0
